### ISSUE TITLE
Lack of Python mapscript documentation

### ISSUE THREAD

**Issue by drnextgis** [MapServer/MapServer-documentation#127]
MapScritp [docs](http://mapserver.org/mapscript/mapscript.html) doesn't contains any information about `fromstring` and `msLoadMapFromString` functions:

```
>>> import mapscript
>>> mapscript.fromstring
<function fromstring at 0x7f2ffdd47320>
>>> mapscript.msLoadMapFromString
<built-in function msLoadMapFromString>
```

**Comment by jmckenna** [comment]
@drnextgis Can you confirm that these 2 functions are exposed to both SWIG mapscript & PHP mapscript? (maybe you are setup to test both of these in SWIG & PHP)

Also, if you are familiar with both functions, maybe you can create a pull request for this update to the docs?

**Comment by geographika** [comment]
Docs should now be in sync with code following https://mapserver.org/development/rfc/ms-rfc-132.html
See docs online at https://mapserver.org/mapscript/mapscript-api/ which include all module-level functions such as ``fromstring``.
