### ISSUE TITLE
PHP MapScript doc missing insertStyle

### ISSUE THREAD

**Issue by sdlime** [MapServer/MapServer-documentation#237]
If http://mapserver.org/mapscript/php/phpmapscript.htm is being kept up-to-date . . .

deleteStyle is listed in a couple of places, but insertStyle isn't, even though it's available.

I do see both listed under SWIG, though.

Rock on!

(submitted as https://github.com/mapserver/mapserver/issues/5542 by @cgalvarino)

**Comment by jmckenna** [comment]
will take a look

**Comment by jmckenna** [comment]
Finally added through pull request #364
