### ISSUE TITLE
Revise PackageListing Page to Show that OSGeo4W Installs of MapServer are Not Supported or Have Deprecated

### ISSUE THREAD

**Issue by NathanTylerLowry** [MapServer/MapServer-documentation#381]
MapServer Documentation Folks,

Please revise https://trac.osgeo.org/osgeo4w/wiki/PackageListing to show that Mapserver versions installed by way of OSGeo4W installation executables are not supported or have deprecated since the MapServer 5.0 release similar to how it is shown on the same page for FWTools.

https://trac.osgeo.org/osgeo4w/wiki/PackageListing reads in part:
"Windows 

MS4W 
MapServer for Windows. If you are a beginner looking for a complete MapServer solution on the Windows platform, or an advanced user looking to avoid compiling your own, this is what you’re looking for. MS4W is a complete Web Server/MapServer/MapScript package. MS4W includes several flavors of MapScript (PHP, C#, Python, Java), and additional dlls for Oracle support. Several popular Web applications are also available for download, which are pre-configured for MS4W.

OSGeo4W
OSGeo4W is a binary distribution of a broad set of Open Source geospatial software for Win32 environments (Windows XP, Vista, etc). OSGeo4W includes GDAL/OGR, GRASS, MapServer, OpenEV, uDig, as well as many other packages.

Deprecated since version 2006:
FWTools
A collection of Open Source GIS tools provided by Frank Warmerdam. This goes beyond your basic web mapping tools and include many useful utilities for creating, manipulating, and serving geo-spatial data. New versions will probably not appear.

Gisinternals
A collection of binary packages that are compiled daily based on the MapServer and GDAL SVN (development and stable branches)."

While https://mapserver.org/installation/iis.html#configuring-with-iis reads in part:

"MapServer Setup
Precompiled versions of MapServer and GDAL (a required dependency) can be downloaded from http://www.gisinternals.com/release.php. These downloads are built and maintained by Tamas Szekeres a long term contributor to MapServer, and Project Steering Committee (PSC) member.

Note Which version should I download?
Unless you are using deprecated features in your Mapfiles you should download the latest stable release.

Nearly all servers will now have a x64 (64-bit) architecture, so unless you are restricted to a win32 (32-bit) server download a x64 release.

Unless you have a good reason you should use the latest compiler version. MSVC 2013 means the binaries were compiled with using Visual C++ 2013. If you rely on Python2 Mapscript you will need to use the MSVC 2008 version so that it matches the version Python2 was compiled with.

This installation guide uses the 'Compiled binaries in a single .zip package' download (release-1800-x64-gdal-2-1-3-mapserver-7-0-4). There is also a “MapServer installer with IIS registration support” option but at the time of writing this did not install successfully."

https://trac.osgeo.org/osgeo4w/wiki/PackageListing however makes it more obvious that installations of MapServer from OSGeo4W are not currently supported by reading in part:

"MapServer (unmaintained)
5.0.x (stable)
pkg-mapserver: MapServer CGI
pkg-mapscript-java: Java MapScript
pkg-mapscript-python: Python MapScript
pkg-php_mapscript?: MapScript extension for PHP"

Thanks!

Nathan Tyler Lowry
Comprehensive GIS Solutions
(719) 208-7092 Desk
(719) 963-3571 Cell
Nathan.Tyler.Lowry@gmail.com

**Comment by jmckenna** [comment]
thanks for this feedback @NathanTylerLowry These changes should be visible on the live website in about 10 minutes.

**Comment by jratike80** [comment]
My OSGeo4W installer shows Mapserver 6.4.1 on the list.  The version is old, but the referred wiki page is old as well, last updated 22 months ago.
