### ISSUE TITLE
Integrate the PHP mapscript and SWIG mapscript documentation

### ISSUE THREAD

**Issue by havatv** [MapServer/MapServer-documentation#41]
In mapserver/mapserver#4347, @sdlime wrote:

> Man, I wish we could have just one for the MapScript API document and then language specific implementation notes

and

> One thing about merging MapScript docs is that would help surface differences in the API. Hard as we might try things are not identical. I am ok with a phased approach, that is, complete the work mentioned in this ticket and then move separately to unify all MapScript docs. Jeff, thoughts?

@jmckenna commented:

> Right now I am happy that the PHP mapscript devs are maintaining the PHP docs directly themselves, very easily. @havatv I am not so sure how we could have one document home for mapscript, when the PHP and SWIG APIs are different.

And @sdlime commented:

> I looked through docs a bit and it looks like both are relatively current. Formats are just very different. There is loads of overlap though that is pretty language agnostic. For example, the list of class members/attributes...

The discussion can continue here.
How should a unified mapscript API documentation be structured?

**Comment by geographika** [comment]
With the move to SWIG of PHP MapScript I think this can now be closed.
