### ISSUE TITLE
The migration guide needs to be better integrated with the documentation

### ISSUE THREAD

**Issue by tbonfort** [MapServer/MapServer-documentation#55]
(migrated from mapserver/mapserver#4472)

The migration guide is living in mapserver / mapserver.
We need to have the migration guide better integrated with the documentation.
Currently, on mapserver.org/trunk, the migration guide is the one for 6.0 (it should be the one for 6.2).

In track there used to be a mechanism to "copy" the migration guide over to the documentation.
Such a copy should be done every time the documentation is compiled.

It could perhaps also be useful to include the migration guide in the PDF documentation.

**Comment by havatv** [comment]
The current status is that there is a link to the migration guide on the top of the documentation "front page".  The migration guide is not included in the PDF, except for the line on the first page that says "If you are upgrading from an earlier version of MapServer, be sure to review the MapServer Migration Guide" (no link).
@jmckenna, @tbonfort, should the migration guide be included in the PDF (and then I guess it would also have to be included in the documentation)?  If not, this issue could be closed.
(the PHP mapscript migration guide is included in the PDF)
