### ISSUE TITLE
Swig/MapScript Query Docs Out-of-date

### ISSUE THREAD

**Issue by tbonfort** [MapServer/MapServer-documentation#56]
(moved from mapserver/mapserver#4414)

The page http://mapserver.org/mapscript/querying.html needs to be updated to reflect changes made between 5.6 and 6.0. Specifically, the code for query results processing has changed significantly. See http://mapserver.org/development/rfc/ms-rfc-65.html for more information. The PHP/MapScript docs don't seem to have a similar set of docs.

**Comment by geographika** [comment]
https://mapserver.org/mapscript/querying.html was updated with new API as part of https://mapserver.org/development/rfc/ms-rfc-132.html
