### ISSUE TITLE
Compfilter description is missing in the COMPISTE page

### ISSUE THREAD

**Issue by LarsSchy** [MapServer/MapServer-documentation#677]
Information to add to this page:

https://mapserver.org/mapfile/composite.html?highlight=compop

COMPFILTER
 The currently available filters are:
 - "blur(integer)"
 - "translate(integer,integer)"
 - "grayscale()"
 - "blacken()"
 - "whiten()"

**Comment by geographika** [comment]
@LarsSchy - does this keyword have any effect on the output? Looking at the code it doesn't appear to be used anywhere: https://github.com/MapServer/MapServer/search?q=COMPFILTER

The RFC states: `COMPFILTER "foo" #reserved for future use` - https://mapserver.org/development/rfc/ms-rfc-113.html#proposed-enhancement so maybe it was added in preparation for future development?

**Comment by LarsSchy** [comment]
Yes, it has effect.  I created one example mapfile that uses all five of those filters today.
https://gist.github.com/LarsSchy/4aa75fd2a6bc7eb01a7cff9beb64b59a

The original info I read, is in this users-list entry by Thomas B.
https://lists.osgeo.org/pipermail/mapserver-users/2015-October/078298.html

**Comment by LarsSchy** [comment]
Glad You found it :-)

**Comment by jmckenna** [comment]
Fixed by @LarsSchy .  Closing.
