### ISSUE TITLE
suggested improvements on docs for building docs

### ISSUE THREAD

**Issue by pvgenuchten** [MapServer/MapServer-documentation#836]
i tried to build docs on a clean system, some findings which maybe should be included on docs (Ubuntu)

Error:
```
msgfmt command not found
```
Is related to missing gettext
```
apt-get install gettext
```

Error:
```
ModuleNotFoundError: No module named 'mapscript'
```
Missing in requirements.txt?
```
pip install mapscript
```

Error:

```
/MapServer-documentation/en/mapscript/mapscript-api/functions.rst:5: WARNING: autosummary: failed to import mapscript.shapeObj_fromWKT.
Possible hints:
* ModuleNotFoundError: No module named 'mapscript.shapeObj_fromWKT'
```

**Comment by jmckenna** [comment]
@pvgenuchten do the changes proposed through https://github.com/MapServer/MapServer-documentation/pull/839 help?  (please give it a review).  Thanks!
